version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: cargo
    directory: /packages/schnorrkel-wasm/rust
    schedule:
      interval: daily
    open-pull-requests-limit: 20
