name: Publish
description: Publish to NPM
runs:
  using: composite
  steps:
    - run: pnpm pack && mv *.tgz package.tgz
      shell: bash
      working-directory: ./packages/hdkd
    - uses: JS-DevTools/npm-publish@v4
      with:
        package: ./packages/hdkd/package.tgz
        access: public
        provenance: true
    - run: pnpm pack && mv *.tgz package.tgz
      shell: bash
      working-directory: ./packages/hdkd-helpers
    - uses: JS-DevTools/npm-publish@v4
      with:
        package: ./packages/hdkd-helpers/package.tgz
        access: public
        provenance: true
    - run: pnpm pack && mv *.tgz package.tgz
      shell: bash
      working-directory: ./packages/schnorrkel-wasm
    - uses: JS-DevTools/npm-publish@v4
      with:
        package: ./packages/schnorrkel-wasm/package.tgz
        access: public
        provenance: true
