name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            packages/schnorrkel-wasm/rust/
          key: ${{ runner.os }}-cargo-${{ hashFiles('packages/schnorrkel-wasm/rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - run: which wasm-pack || cargo install wasm-pack
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - run: pnpm lint
      - uses: ./.github/actions/publish
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.NPM_TOKEN }}
